import sys
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(675, 652)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabTasks = QtWidgets.QTabWidget(self.centralwidget)
        self.tabTasks.setGeometry(QtCore.QRect(10, 9, 651, 601))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tabTasks.setFont(font)
        self.tabTasks.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabTasks.setTabsClosable(False)
        self.tabTasks.setMovable(True)
        self.tabTasks.setObjectName("tabTasks")
        self.currentTasks = QtWidgets.QWidget()
        self.currentTasks.setObjectName("currentTasks")
        self.toDoButton = QtWidgets.QPushButton(self.currentTasks)
        self.toDoButton.setGeometry(QtCore.QRect(10, 70, 121, 41))
        self.toDoButton.setObjectName("toDoButton")
        self.inProgressButton = QtWidgets.QPushButton(self.currentTasks)
        self.inProgressButton.setGeometry(QtCore.QRect(250, 70, 121, 41))
        self.inProgressButton.setObjectName("inProgressButton")
        self.DoneButton = QtWidgets.QPushButton(self.currentTasks)
        self.DoneButton.setGeometry(QtCore.QRect(500, 70, 121, 41))
        self.DoneButton.setObjectName("DoneButton")
        self.deleteTskButton = QtWidgets.QPushButton(self.currentTasks)
        self.deleteTskButton.setGeometry(QtCore.QRect(10, 510, 121, 41))
        self.deleteTskButton.setObjectName("deleteTskButton")
        self.clearButton = QtWidgets.QPushButton(self.currentTasks)
        self.clearButton.setGeometry(QtCore.QRect(140, 510, 121, 41))
        self.clearButton.setObjectName("clearButton")
        self.toDoLabel = QtWidgets.QLabel(self.currentTasks)
        self.toDoLabel.setGeometry(QtCore.QRect(10, 130, 191, 361))
        self.toDoLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.toDoLabel.setObjectName("toDoLabel")
        self.inProgressLabel = QtWidgets.QLabel(self.currentTasks)
        self.inProgressLabel.setGeometry(QtCore.QRect(220, 130, 191, 361))
        self.inProgressLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.inProgressLabel.setObjectName("inProgressLabel")
        self.doneLabel = QtWidgets.QLabel(self.currentTasks)
        self.doneLabel.setGeometry(QtCore.QRect(430, 130, 191, 361))
        self.doneLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.doneLabel.setObjectName("doneLabel")
        self.lineEdit = QtWidgets.QLineEdit(self.currentTasks)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 611, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.tabTasks.addTab(self.currentTasks, "")
        self.historyTasks = QtWidgets.QWidget()
        self.historyTasks.setObjectName("historyTasks")
        self.historyTasks_2 = QtWidgets.QLabel(self.historyTasks)
        self.historyTasks_2.setGeometry(QtCore.QRect(10, 40, 621, 491))
        self.historyTasks_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.historyTasks_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.historyTasks_2.setObjectName("historyTasks_2")
        self.tabTasks.addTab(self.historyTasks, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 675, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabTasks.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toDoButton.setText(_translate("MainWindow", "To do"))
        self.inProgressButton.setText(_translate("MainWindow", "In progress"))
        self.DoneButton.setText(_translate("MainWindow", "Done"))
        self.deleteTskButton.setText(_translate("MainWindow", "Delete Task"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
        self.toDoLabel.setText(_translate("MainWindow", "To do list"))
        self.inProgressLabel.setText(_translate("MainWindow", "tasks in progress"))
        self.doneLabel.setText(_translate("MainWindow", "Tasks completed"))
        self.tabTasks.setTabText(self.tabTasks.indexOf(self.currentTasks), _translate("MainWindow", "Current tasks"))
        self.historyTasks_2.setText(_translate("MainWindow", "history tasks"))
        self.tabTasks.setTabText(self.tabTasks.indexOf(self.historyTasks), _translate("MainWindow", "History tasks"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
    with open("style.qss", "r") as f:
        app.setStyleSheet(f.read())